import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("production API protects foundation resources",async()=>{const api=await readFile(new URL("../server/index.mjs",import.meta.url),"utf8");const normalized=api.replaceAll("\\","");for(const route of ["/api/auth/login","/api/auth/logout","/api/me","/api/departments","/api/employees","/api/approvals"])assert.ok(normalized.includes(route));for(const control of ["requireSession","requirePermission","audit","transaction"])assert.match(api,new RegExp(control));assert.match(api,/greatest\(next_value,/);assert.match(api,/max\(substring\(employee_number/);});
test("employee password reset is available in the staff drawer",async()=>{const [client,app]=await Promise.all([readFile(new URL("../app/api-client.ts",import.meta.url),"utf8"),readFile(new URL("../app/frame-app.tsx",import.meta.url),"utf8")]);assert.match(client,/resetEmployeePassword/);assert.match(app,/Reset temporary password/);assert.match(app,/shown once/);});
test("navigation is generated from the signed-in employee permissions",async()=>{const [api,app]=await Promise.all([readFile(new URL("../server/index.mjs",import.meta.url),"utf8"),readFile(new URL("../app/frame-app.tsx",import.meta.url),"utf8")]);assert.match(api,/permissions:rows\.map/);assert.match(app,/modulePermissions/);assert.match(app,/allowedNav/);assert.match(app,/setPermissions\(access\.permissions\)/);});
test("normal employees have read-only assigned tasks and own KPI",async()=>{const [api,app,migrator,migration]=await Promise.all([readFile(new URL("../server/index.mjs",import.meta.url),"utf8"),readFile(new URL("../app/frame-app.tsx",import.meta.url),"utf8"),readFile(new URL("../server/migrate.mjs",import.meta.url),"utf8"),readFile(new URL("../database/008-employee-read-only-tasks.sql",import.meta.url),"utf8")]);assert.match(api,/parts\.push\(`t\.assignee_id=/);assert.doesNotMatch(api,/parts\.push\(`\(t\.assignee_id=.*t\.assigned_by/);assert.match(app,/createPermission/);assert.match(app,/tasks\\\.view\|kpi\\\.view/);assert.match(migrator,/008-employee-read-only-tasks\.sql/);assert.match(migration,/tasks\.create/);assert.match(migration,/tasks\.edit/);assert.match(migration,/kpi\.view/);});
test("dashboard and KPI data follow company department and self scopes",async()=>{const [routes,app]=await Promise.all([readFile(new URL("../server/extended-routes.mjs",import.meta.url),"utf8"),readFile(new URL("../app/frame-app.tsx",import.meta.url),"utf8")]);assert.match(routes,/scope:"self"/);assert.match(routes,/scope:"department"/);assert.match(routes,/scope:"company"/);assert.match(routes,/employee_id=\$/);assert.match(app,/Assigned tasks/);assert.match(app,/My KPI score/);assert.match(app,/My workspace/);});
test("deployment separates web API worker and data services",async()=>{const compose=await readFile(new URL("../deploy/docker-compose.yml",import.meta.url),"utf8");for(const service of ["app:","api:","worker:","postgres:","redis:","nginx:"])assert.match(compose,new RegExp(`\\n  ${service}`));});
