import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";

async function database(){const db=new PGlite({extensions:{pgcrypto}});for(const name of ["schema.sql","modules.sql","remaining-modules.sql","guards.sql","005-production-completion.sql"])await db.exec(await readFile(new URL(`../database/${name}`,import.meta.url),"utf8"));return db;}
async function foundation(db){const company=(await db.query("INSERT INTO companies(name,code) VALUES('FRAME Media Agency','FRAME') RETURNING id")).rows[0];const department=(await db.query("INSERT INTO departments(company_id,name,code) VALUES($1,'Administration','ADM') RETURNING id",[company.id])).rows[0];const requester=(await db.query("INSERT INTO employees(company_id,employee_number,department_id,first_name,last_name,work_email,job_title,status) VALUES($1,'FRM-0001',$2,'Ada','One','ada@frame.test','Staff','active') RETURNING id",[company.id,department.id])).rows[0];const manager=(await db.query("INSERT INTO employees(company_id,employee_number,department_id,first_name,last_name,work_email,job_title,status) VALUES($1,'FRM-0002',$2,'Max','Two','max@frame.test','Manager','active') RETURNING id",[company.id,department.id])).rows[0];await db.query("UPDATE employees SET manager_id=$1 WHERE id=$2",[manager.id,requester.id]);return{company,department,requester,manager};}

test("approval trigger notifies current manager and rejection updates business state",{timeout:120000},async()=>{const db=await database();const {company,requester,manager}=await foundation(db);const definition=(await db.query("INSERT INTO workflow_definitions(company_id,workflow_key,name,version,definition,created_by) VALUES($1,'leave','Leave',1,'{}',$2) RETURNING id",[company.id,requester.id])).rows[0];const leave=(await db.query("INSERT INTO leave_requests(employee_id,leave_type,starts_on,ends_on,reason,status) VALUES($1,'annual',current_date,current_date,'Test','pending') RETURNING id",[requester.id])).rows[0];const request=(await db.query("INSERT INTO approval_requests(company_id,workflow_definition_id,entity_type,entity_id,title,requested_by,status,submitted_at) VALUES($1,$2,'leave_request',$3,'Approve leave',$4,'pending',now()) RETURNING id",[company.id,definition.id,leave.id,requester.id])).rows[0];await db.query("INSERT INTO approval_steps(request_id,step_number,assignee_type,assignee_ref,status) VALUES($1,1,'manager','direct','pending')",[request.id]);const notice=await db.query("SELECT recipient_id,type FROM notifications WHERE entity_id=$1",[leave.id]);assert.equal(notice.rows[0].recipient_id,manager.id);assert.equal(notice.rows[0].type,"approval_required");await db.query("UPDATE approval_requests SET status='rejected' WHERE id=$1",[request.id]);assert.equal((await db.query("SELECT status FROM leave_requests WHERE id=$1",[leave.id])).rows[0].status,"rejected");assert.equal((await db.query("SELECT count(*)::int count FROM notifications WHERE recipient_id=$1 AND type='approval_rejected'",[requester.id])).rows[0].count,1);await db.close();});

test("journal posting accepts balanced lines and rejects unbalanced lines",{timeout:120000},async()=>{const db=await database();const {company,requester}=await foundation(db);const cash=(await db.query("INSERT INTO accounts(company_id,code,name,account_type) VALUES($1,'1000','Cash','asset') RETURNING id",[company.id])).rows[0];const revenue=(await db.query("INSERT INTO accounts(company_id,code,name,account_type) VALUES($1,'4000','Revenue','revenue') RETURNING id",[company.id])).rows[0];const balanced=(await db.query("INSERT INTO journal_entries(company_id,reference,entry_date,description,status) VALUES($1,'J-1',current_date,'Balanced','draft') RETURNING id",[company.id])).rows[0];await db.query("INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,currency) VALUES($1,$2,100,0,'RWF'),($1,$3,0,100,'RWF')",[balanced.id,cash.id,revenue.id]);await db.query("UPDATE journal_entries SET status='posted',posted_by=$2 WHERE id=$1",[balanced.id,requester.id]);const unbalanced=(await db.query("INSERT INTO journal_entries(company_id,reference,entry_date,description,status) VALUES($1,'J-2',current_date,'Unbalanced','draft') RETURNING id",[company.id])).rows[0];await db.query("INSERT INTO journal_lines(journal_entry_id,account_id,debit,credit,currency) VALUES($1,$2,100,0,'RWF'),($1,$3,0,90,'RWF')",[unbalanced.id,cash.id,revenue.id]);await assert.rejects(db.query("UPDATE journal_entries SET status='posted',posted_by=$2 WHERE id=$1",[unbalanced.id,requester.id]),/balance/);await db.close();});
