import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("every writable module tab has live create or update wiring",async()=>{const [ui,api]=await Promise.all([readFile(new URL("../app/frame-app.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api-client.ts",import.meta.url),"utf8")]);for(const token of ["tabForms","canCreate","editConfig","EditDrawer","Save changes"])assert.match(ui,new RegExp(token));for(const resource of ["services","clientReports","complaints","meetings","dailyReports","discipline","recruitment","invoices","payroll","budgets","assetRequests","suppliers","subscriptions"])assert.match(ui,new RegExp(`frameApi\\.${resource}`));assert.match(api,/method:"PATCH"/);});

test("deployment has migration gate health checks and shared exports",async()=>{const compose=await readFile(new URL("../deploy/docker-compose.yml",import.meta.url),"utf8");assert.match(compose,/migrate:/);assert.match(compose,/service_completed_successfully/);assert.match(compose,/frame_exports:\/var\/lib\/frame\/exports:ro/);assert.match(compose,/api\/health/);});

test("production worker sends channels retries reminders and exports",async()=>{const worker=await readFile(new URL("../worker/jobs.mjs",import.meta.url),"utf8");for(const token of ["queueDailyReportReminders","sendWhatsApp","transporter.sendMail","processDeliveries","processJobs","processExports","completed_at=now()","attempts+1>=5"])assert.match(worker,new RegExp(token.replace(/[+()]/g,"\\$&")));});

test("approval inbox filters current authority and database automates notifications and rejection",async()=>{const [index,migration]=await Promise.all([readFile(new URL("../server/index.mjs",import.meta.url),"utf8"),readFile(new URL("../database/005-production-completion.sql",import.meta.url),"utf8")]);for(const view of ["submitted","completed","mine"])assert.match(index,new RegExp(`view===\\"${view}\\"`));assert.match(index,/requested\.manager_id/);assert.match(index,/r\.name=ast\.assignee_ref/);for(const token of ["approval_authority_notification","approval_required","approval_rejection_outcome","approval_rejected"])assert.match(migration,new RegExp(token));});

test("forward migration and bootstrap permissions include completion features",async()=>{const [migration,migrator,seed]=await Promise.all([readFile(new URL("../database/005-production-completion.sql",import.meta.url),"utf8"),readFile(new URL("../server/migrate.mjs",import.meta.url),"utf8"),readFile(new URL("../server/seed.mjs",import.meta.url),"utf8")]);assert.match(migration,/completed_at/);assert.match(migration,/asset_requests/);assert.match(migrator,/005-production-completion\.sql/);for(const permission of ["attendance.view","accounting.view","reports.view","kpi.finalize","assets.submit"])assert.match(seed,new RegExp(permission.replace(".","\\.")));});

test("exports require source visibility and proxy replaces untrusted forwarded IP",async()=>{const [routes,nginx]=await Promise.all([readFile(new URL("../server/extended-routes.mjs",import.meta.url),"utf8"),readFile(new URL("../deploy/nginx.conf",import.meta.url),"utf8")]);assert.match(routes,/reportPermissions/);assert.match(routes,/audit\.view/);assert.match(routes,/requirePermission\(s\.employee_id,reportPermissions/);assert.doesNotMatch(nginx,/proxy_add_x_forwarded_for/);assert.match(nginx,/X-Forwarded-For \$remote_addr/);});
