"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { frameApi } from "./api-client";
import "./simple-workspace.css";

type Item=Record<string,unknown>;
const labels:Record<string,string>={"Daily report":"Daily report","Follow-ups":"Sales follow-ups",Tasks:"My tasks",KPI:"KPI results",Leave:"Leave requests",Leaves:"Leave requests",Budget:"Budget requests",Employees:"Employees",Assets:"Company assets",Reports:"Department reports",Overview:"Overview"};
function date(v:unknown){return v?new Date(String(v)).toLocaleString("en-RW",{dateStyle:"medium",timeStyle:"short"}):"—"}
function typeFor(kind:string){return kind==="production"?"production_company":kind==="marketing"?"marketing_daily":"sales_daily"}

export function SimpleWorkspace({onLogout}:{onLogout:()=>Promise<void>}){
 const [profile,setProfile]=useState<{employeeId:string;employeeNumber:string;name:string;department:string;kind:string;roles:string[]}|null>(null); const [menu,setMenu]=useState<string[]>([]);const [active,setActive]=useState("Overview");const [rows,setRows]=useState<Item[]>([]);const [departments,setDepartments]=useState<Item[]>([]);const [roles,setRoles]=useState<Item[]>([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [form,setForm]=useState(false);
 const privileged=profile?.kind==="admin"||profile?.kind==="ceo"||profile?.kind==="hr";
 async function load(){setLoading(true);try{const w=await frameApi.simpleWorkspace();setProfile(w.profile);setMenu(w.menu);if(!w.menu.includes(active))setActive(w.menu[0]||"Overview");}catch(e){setMessage(e instanceof Error?e.message:"Could not load workspace");}finally{setLoading(false)}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!profile)return; let fetcher:()=>Promise<{data:Item[]}>|null=null;if(active==="Daily report"||active==="Reports")fetcher=frameApi.simpleReports;else if(active==="Follow-ups")fetcher=frameApi.simpleFollowups;else if(active==="Budget")fetcher=frameApi.simpleBudgets;else if(active==="Leave"||active==="Leaves")fetcher=frameApi.simpleLeaves;else if(active==="Tasks")fetcher=frameApi.simpleTasks;else if(active==="Employees"){fetcher=frameApi.simpleEmployees;frameApi.simpleDepartments().then(result=>setDepartments(result.data)).catch(()=>setDepartments([]));frameApi.simpleRoles().then(result=>setRoles(result.data)).catch(()=>setRoles([]));}else if(active==="Assets")fetcher=frameApi.simpleAssets;if(!fetcher){setRows([]);return;}setLoading(true);fetcher().then(result=>setRows(result.data)).catch(e=>setMessage(e instanceof Error?e.message:"Could not load records")).finally(()=>setLoading(false));},[active,profile?.kind]);
 const heading=labels[active]||active;
 const action=active==="Employees"&&privileged?"Add employee":active==="Daily report"?"Submit report":active==="Follow-ups"?"Add follow-up":active==="Budget"?"Request budget":active==="Leave"||active==="Leaves"?"Request leave":active==="Tasks"&&(profile?.kind==="ceo"||profile?.kind==="admin"||profile?.kind==="sales_manager")?"Assign task":null;
 const summary=useMemo(()=>({open:rows.filter(r=>String(r.status||"")==="pending").length,total:rows.length,onTime:rows.filter(r=>r.submitted_on_time).length}),[rows]);
 async function decision(id:string,decision:"approved"|"rejected",kind:"budget"|"leave"){try{if(kind==="budget")await frameApi.decideSimpleBudget(id,{decision});else await frameApi.decideSimpleLeave(id,{decision});setMessage(`Request ${decision}.`);setActive("Overview");setTimeout(()=>setActive(kind==="budget"?"Budget":"Leaves"),0);}catch(e){setMessage(e instanceof Error?e.message:"Decision failed");}}
 return <main className="simple-shell"><aside><div className="simple-brand"><b>F</b><span>FRAME <small>OS</small></span></div><div className="simple-person"><strong>{profile?.name||"Loading"}</strong><span>{profile?.employeeNumber} · {profile?.department}</span></div><nav>{menu.map(name=><button key={name} onClick={()=>{setActive(name);setForm(false);setMessage("")}} className={active===name?"active":""}><i>{name==="Overview"?"⌂":name==="Tasks"?"✓":name==="Budget"?"◇":name.includes("Leave")?"◷":name==="Employees"?"♙":name==="Follow-ups"?"↗":"▤"}</i>{labels[name]||name}</button>)}</nav><button className="sign-out" onClick={()=>onLogout()}>↪ Sign out</button></aside><section className="simple-main"><header><div><p>{profile?.department||"System administration"}</p><h1>{heading}</h1></div><div><span className="today">{new Intl.DateTimeFormat("en-RW",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</span>{action?<button className="primary" onClick={()=>setForm(true)}>＋ {action}</button>:null}</div></header>{message?<div className="simple-message">{message}<button onClick={()=>setMessage("")}>×</button></div>:null}{active==="Overview"?<section className="overview"><article><span>My department</span><strong>{profile?.department||"System Admin"}</strong><small>{profile?.roles.join(", ")||"Employee"}</small></article><article><span>Records requiring action</span><strong>{summary.open}</strong><small>Pending decisions or requests</small></article><article><span>Current records</span><strong>{summary.total}</strong><small>Latest information appears first</small></article><article><span>Reports on time</span><strong>{summary.onTime}</strong><small>Submitted within 17:30–19:30</small></article><div className="simple-guide"><h2>Start here</h2><p>Use the menu to enter your department’s daily report, assigned work, leave request, budget request, or sales follow-ups. Every entry is time-recorded automatically.</p></div></section>:<section className="simple-panel">{form?<EntryForm active={active} kind={profile?.kind||"employee"} departments={departments} roles={roles} close={()=>setForm(false)} done={(text)=>{setForm(false);setMessage(text);setActive("Overview");setTimeout(()=>setActive(active),0);}}/>:<><div className="panel-title"><p>{loading?"Loading records…":`${rows.length} record${rows.length===1?"":"s"}`}</p><span>Newest first</span></div><input className="record-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records…"/><Records active={active} rows={rows} query={search} privileged={privileged} onDecision={decision}/></>}</section>}</section></main>
}

function Records({active,rows,query,privileged,onDecision}:{active:string;rows:Item[];query:string;privileged:boolean;onDecision:(id:string,d:"approved"|"rejected",k:"budget"|"leave")=>void}){const filtered=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));if(!filtered.length)return <div className="empty"><strong>{rows.length?"No matching records":"No records yet"}</strong><p>{rows.length?"Try another search.":"Create the first record using the button above."}</p></div>;const keys=active==="Employees"?["employee_number","first_name","last_name","department","job_title","salary","status"]:active==="Tasks"?["title","assignee","deadline","progress","display_status"]:active==="Budget"?["created_at","department","amount","reason","status"]:active.includes("Leave")?["employee","starts_on","ends_on","reason","status"]:active==="Follow-ups"?["company_name","contact_name","service_offer","stage","created_at"]:active==="Assets"?["asset_number","name","category","value","assigned_person","condition","status"]:["submitted_at","employee","report_type","reporting_score","submitted_on_time"];return <div className="table-scroll"><table className="records-table"><thead><tr>{keys.map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((row,index)=><tr key={String(row.id||index)}>{keys.map(key=><td key={key}>{key.includes("status")?<b className={`state ${String(row[key]||"record").replaceAll(" ","-")}`}>{String(row[key]||"—")}</b>:key.includes("at")||key==="deadline"?date(row[key]):String(row[key]??"—")}</td>)}<td>{privileged&&String(row.status)==="pending"&&(active==="Budget"||active.includes("Leave"))?<span className="decisions"><button onClick={()=>onDecision(String(row.id),"approved",active==="Budget"?"budget":"leave")}>Approve</button><button onClick={()=>onDecision(String(row.id),"rejected",active==="Budget"?"budget":"leave")}>Reject</button></span>:"—"}</td></tr>)}</tbody></table></div>}

function EntryForm({active,kind,departments,roles,close,done}:{active:string;kind:string;departments:Item[];roles:Item[];close:()=>void;done:(s:string)=>void}){
 const [saving,setSaving]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{if(active==="Employees"){const result=await frameApi.createSimpleEmployee(Object.fromEntries(f.entries()));done(`Employee created. One-time password: ${result.temporaryPassword}`);}else if(active==="Daily report"){const payload=Object.fromEntries([...f.entries()].filter(([k])=>k!=="reportDate"));await frameApi.createSimpleReport({reportType:typeFor(kind),reportDate:f.get("reportDate"),payload});done("Daily report submitted and time recorded.");}else if(active==="Follow-ups"){await frameApi.createSimpleFollowup({companyName:f.get("companyName"),contactName:f.get("contactName"),contactTitle:f.get("contactTitle"),phone:f.get("phone"),serviceOffer:f.get("serviceOffer"),stage:f.get("stage"),note:f.get("note")});done("Follow-up added.");}else if(active==="Budget"){await frameApi.createSimpleBudget({amount:Number(f.get("amount")),reason:f.get("reason")});done("Budget request sent.");}else if(active==="Leave"||active==="Leaves"){await frameApi.createSimpleLeave({startsOn:f.get("startsOn"),endsOn:f.get("endsOn"),reason:f.get("reason")});done("Leave request sent.");}else if(active==="Tasks"){await frameApi.createSimpleTask({title:f.get("title"),description:f.get("description"),assigneeId:f.get("assigneeId"),deadline:f.get("deadline")});done("Task assigned.");}}catch(err){done(err instanceof Error?err.message:"Could not save record");}finally{setSaving(false)}}
 if(active==="Employees")return <form className="entry-form" onSubmit={submit}><h2>Add employee</h2><p className="form-note">Employee ID is generated automatically after creation.</p><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>Phone number<input name="phone" required/></label><label>Address<input name="address" required/></label><label>Salary (RWF)<input name="salary" type="number" min="0" required/></label><label>Equity Bank account<input name="bankAccount" required/></label><label>Hiring date<input name="hiringDate" type="date" required/></label><label>Payment day<input name="paymentDay" type="number" min="1" max="31" placeholder="Example: 25" required/></label><label>Work email (optional)<input name="workEmail" type="email"/></label><label>Job title<input name="jobTitle" defaultValue="Employee" required/></label><label>Department<select name="departmentId" required defaultValue=""><option value="" disabled>Select department</option>{departments.map(d=><option key={String(d.id)} value={String(d.id)}>{String(d.name)}</option>)}</select></label><label>Access role<select name="roleName" required defaultValue=""><option value="" disabled>Select role</option>{roles.map(r=><option key={String(r.name)} value={String(r.name)}>{String(r.name)}</option>)}</select></label><div><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving?"Creating…":"Create employee"}</button></div></form>;
 const fields=active==="Daily report"?[["reportDate","Report date","date"],["completed","Work completed","text"],["clientResults","Client or sales results","text"],["note","Notes","text"]]:active==="Follow-ups"?[["companyName","Company name","text"],["contactName","Contact name","text"],["contactTitle","Contact title","text"],["phone","Phone","text"],["serviceOffer","Service offered","text"],["stage","Stage: initial, middle, rejected or approved","text"],["note","Note","text"]]:active==="Budget"?[["amount","Amount (RWF)","number"],["reason","Reason","text"]]:active.includes("Leave")?[["startsOn","Leave starts","date"],["endsOn","Return date","date"],["reason","Reason","text"]]:[["title","Task title","text"],["assigneeId","Employee ID to assign","text"],["deadline","Deadline","datetime-local"],["description","Description","text"]];return <form className="entry-form" onSubmit={submit}><h2>{active}</h2>{fields.map(([name,label,type])=><label key={name}>{label}<input name={name} type={type} required={name!=="note"&&name!=="description"}/></label>)}<div><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Save"}</button></div></form>
}
