import { createReadStream } from "node:fs";
import { stat } from "node:fs/promises";
import path from "node:path";
import { pool,transaction,audit } from "./db.mjs";
import { jsonBody,requestContext,requirePermission,requireSession,send } from "./http.mjs";

export function registerAdminRoutes(route){
 route("GET",/^\/api\/search$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"search.global",["company"]);const q=new URL(req.url,"http://localhost").searchParams.get("q")?.trim();if(!q||q.length<2)return send(res,200,{data:[]});const like=`%${q}%`;const {rows}=await pool.query(`SELECT 'customer' type,id,customer_number reference,business_name label FROM customers WHERE company_id=$1 AND (customer_number ILIKE $2 OR business_name ILIKE $2 OR phone ILIKE $2 OR email ILIKE $2)
 UNION ALL SELECT 'employee',id,employee_number,first_name||' '||last_name FROM employees WHERE company_id=$1 AND (employee_number ILIKE $2 OR first_name ILIKE $2 OR last_name ILIKE $2 OR work_email ILIKE $2)
 UNION ALL SELECT 'contract',id,contract_number,contract_number FROM contracts WHERE company_id=$1 AND contract_number ILIKE $2
 UNION ALL SELECT 'task',id,id::text,title FROM tasks WHERE company_id=$1 AND title ILIKE $2 LIMIT 50`,[s.company_id,like]);send(res,200,{data:rows});});
 route("GET",/^\/api\/roles$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"roles.configure",["company"]);const {rows}=await pool.query(`SELECT r.id,r.name,r.description,r.status,json_agg(json_build_object('key',p.permission_key,'scope',rp.scope) ORDER BY p.permission_key) FILTER(WHERE p.id IS NOT NULL) permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE r.company_id=$1 GROUP BY r.id ORDER BY r.name`,[s.company_id]);send(res,200,{data:rows});});
 route("POST",/^\/api\/roles$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"roles.configure",["company"]);const b=await jsonBody(req);if(!b.name)throw Object.assign(new Error("Role name is required"),{status:400});const role=await transaction(async c=>{const created=(await c.query("INSERT INTO roles(company_id,name,description) VALUES($1,$2,$3) RETURNING *",[s.company_id,b.name,b.description||null])).rows[0];for(const grant of b.permissions||[]){const permission=(await c.query("SELECT id FROM permissions WHERE permission_key=$1",[grant.key])).rows[0];if(permission)await c.query("INSERT INTO role_permissions(role_id,permission_id,scope) VALUES($1,$2,$3) ON CONFLICT DO NOTHING",[created.id,permission.id,grant.scope]);}return created;});send(res,201,{data:role});});
 route("POST",/^\/api\/employees\/([0-9a-f-]+)\/roles$/,async(req,res,match)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"roles.configure",["company"]);const b=await jsonBody(req);if(!b.roleId)throw Object.assign(new Error("Role ID is required"),{status:400});await pool.query("INSERT INTO employee_roles(employee_id,role_id,department_id,assigned_by) SELECT $1,$2,$3,$4 WHERE EXISTS(SELECT 1 FROM employees WHERE id=$1 AND company_id=$5) ON CONFLICT DO NOTHING",[match[1],b.roleId,b.departmentId||null,s.employee_id,s.company_id]);send(res,201,{ok:true});});
 route("GET",/^\/api\/permissions$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"roles.configure",["company"]);const {rows}=await pool.query("SELECT permission_key,description FROM permissions ORDER BY permission_key");send(res,200,{data:rows});});
 route("GET",/^\/api\/attendance-networks$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"attendance.configure",["company"]);const {rows}=await pool.query("SELECT id,name,allowed_cidr::text allowed_cidr,status,created_at FROM attendance_networks WHERE company_id=$1 ORDER BY name",[s.company_id]);send(res,200,{data:rows});});
 route("POST",/^\/api\/attendance-networks$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"attendance.configure",["company"]);const b=await jsonBody(req);if(!b.allowedCidr)throw Object.assign(new Error("Allowed network CIDR is required"),{status:400});const context=requestContext(req);const record=await transaction(async c=>{const created=(await c.query("INSERT INTO attendance_networks(company_id,name,allowed_cidr) VALUES($1,$2,$3::cidr) RETURNING id,name,allowed_cidr::text allowed_cidr,status,created_at",[s.company_id,b.name||"FRAME MEDIA AGENCY",b.allowedCidr])).rows[0];await audit(c,{companyId:s.company_id,actorId:s.employee_id,action:"attendance.network_create",module:"people",entityType:"attendance_network",entityId:created.id,after:created,requestId:context.requestId,ip:context.ip,userAgent:context.userAgent});return created;});send(res,201,{data:record});});
 route("GET",/^\/api\/attendance-schedules$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"attendance.configure",["company"]);const {rows}=await pool.query("SELECT id,name,department_id,employee_id,weekday,starts_at,ends_at,grace_minutes,status FROM attendance_schedules WHERE company_id=$1 ORDER BY name,weekday",[s.company_id]);send(res,200,{data:rows});});
 route("POST",/^\/api\/attendance-schedules$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"attendance.configure",["company"]);const b=await jsonBody(req);for(const key of ["name","weekday","startsAt","endsAt"])if(b[key]===undefined||b[key]==="")throw Object.assign(new Error(`${key} is required`),{status:400});const context=requestContext(req);const record=await transaction(async c=>{const created=(await c.query("INSERT INTO attendance_schedules(company_id,name,department_id,employee_id,weekday,starts_at,ends_at,grace_minutes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[s.company_id,b.name,b.departmentId||null,b.employeeId||null,Number(b.weekday),b.startsAt,b.endsAt,Number(b.graceMinutes||0)])).rows[0];await audit(c,{companyId:s.company_id,actorId:s.employee_id,action:"attendance.schedule_create",module:"people",entityType:"attendance_schedule",entityId:created.id,after:created,requestId:context.requestId,ip:context.ip,userAgent:context.userAgent});return created;});send(res,201,{data:record});});
 route("GET",/^\/api\/audit$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"audit.view",["company"]);const params=new URL(req.url,"http://localhost").searchParams;const actor=params.get("actor");const values=[s.company_id];let condition="company_id=$1";if(actor){values.push(actor);condition+=" AND actor_employee_id=$2";}const {rows}=await pool.query(`SELECT * FROM audit_events WHERE ${condition} ORDER BY occurred_at DESC LIMIT 500`,values);send(res,200,{data:rows});});
 route("GET",/^\/api\/gm-activity$/,async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"audit.gm_activity",["company"]);const {rows}=await pool.query(`SELECT a.* FROM audit_events a JOIN employee_roles er ON er.employee_id=a.actor_employee_id JOIN roles r ON r.id=er.role_id WHERE a.company_id=$1 AND r.name='General Manager' ORDER BY a.occurred_at DESC LIMIT 500`,[s.company_id]);send(res,200,{data:rows});});
 route("GET",/^\/api\/exports\/([0-9a-f-]+)\/download$/,async(req,res,match)=>{const s=await requireSession(req);const job=(await pool.query("SELECT * FROM export_jobs WHERE id=$1 AND company_id=$2 AND requested_by=$3 AND status='completed' AND expires_at>now()",[match[1],s.company_id,s.employee_id])).rows[0];if(!job)throw Object.assign(new Error("Export is unavailable or expired"),{status:404});const allowedRoot=path.resolve(process.env.EXPORT_DIRECTORY||"/tmp/frame-exports");const file=path.resolve(job.output_reference);if(!file.startsWith(`${allowedRoot}${path.sep}`))throw Object.assign(new Error("Invalid export reference"),{status:400});const info=await stat(file);res.writeHead(200,{"content-type":job.format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","content-length":info.size,"content-disposition":`attachment; filename=frame-${job.report_key}.${job.format}`});createReadStream(file).pipe(res);});
 route("GET",/^\/api\/exports\/([0-9a-f-]+)$/,async(req,res,match)=>{const s=await requireSession(req);const {rows}=await pool.query("SELECT id,report_key,format,status,expires_at,created_at FROM export_jobs WHERE id=$1 AND company_id=$2 AND requested_by=$3",[match[1],s.company_id,s.employee_id]);if(!rows[0])throw Object.assign(new Error("Export not found"),{status:404});send(res,200,{data:rows[0]});});
}
