import { randomUUID } from "node:crypto";
import { pool } from "./db.mjs";
import { tokenHash } from "./security.mjs";

export async function jsonBody(request){const chunks=[];for await(const chunk of request){chunks.push(chunk);if(Buffer.concat(chunks).length>1_000_000)throw Object.assign(new Error("Request too large"),{status:413});}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString("utf8"));}catch{throw Object.assign(new Error("Invalid JSON"),{status:400});}}
export function send(response,status,data,headers={}){response.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers});response.end(JSON.stringify(data));}
export function requestContext(request){return{requestId:request.headers["x-request-id"]||randomUUID(),ip:String(request.headers["x-forwarded-for"]||request.socket.remoteAddress||"").split(",")[0],userAgent:request.headers["user-agent"]||""}}
export function cookie(request,name){const value=request.headers.cookie?.split(";").map(v=>v.trim()).find(v=>v.startsWith(`${name}=`));return value?decodeURIComponent(value.slice(name.length+1)):null}
export async function requireSession(request,{allowPasswordChange=false}={}){const token=cookie(request,"__Host-frame_session");if(!token)throw Object.assign(new Error("Authentication required"),{status:401});const {rows}=await pool.query(`SELECT s.id session_id,s.account_id,e.id employee_id,e.company_id,e.department_id,e.employee_number,e.first_name,e.last_name,e.status,a.must_change_password
  FROM sessions s JOIN user_accounts a ON a.id=s.account_id JOIN employees e ON e.id=a.employee_id
  WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND a.disabled_at IS NULL AND e.status='active'`,[tokenHash(token)]);if(!rows[0])throw Object.assign(new Error("Session expired"),{status:401});if(rows[0].must_change_password&&!allowPasswordChange)throw Object.assign(new Error("Password change required"),{status:428});await pool.query("UPDATE sessions SET expires_at=LEAST(created_at+interval '12 hours',now()+interval '1 hour') WHERE id=$1",[rows[0].session_id]);return rows[0];}
export async function hasPermission(employeeId,key,scopes=["company"]){const {rowCount}=await pool.query(`SELECT 1 FROM employee_roles er JOIN role_permissions rp ON rp.role_id=er.role_id JOIN permissions p ON p.id=rp.permission_id
  WHERE er.employee_id=$1 AND p.permission_key=$2 AND rp.scope=ANY($3::permission_scope[]) AND er.valid_from<=now() AND (er.valid_until IS NULL OR er.valid_until>now()) LIMIT 1`,[employeeId,key,scopes]);return rowCount>0;}
export async function requirePermission(employeeId,key,scopes){if(!await hasPermission(employeeId,key,scopes))throw Object.assign(new Error("Permission denied"),{status:403});}
export async function permissionScopes(employeeId,key){const {rows}=await pool.query(`SELECT DISTINCT rp.scope FROM employee_roles er JOIN role_permissions rp ON rp.role_id=er.role_id JOIN permissions p ON p.id=rp.permission_id WHERE er.employee_id=$1 AND p.permission_key=$2 AND er.valid_from<=now() AND (er.valid_until IS NULL OR er.valid_until>now())`,[employeeId,key]);return rows.map(row=>row.scope);}
export async function requireScopes(employeeId,key,allowed){const scopes=await permissionScopes(employeeId,key);const usable=scopes.filter(scope=>allowed.includes(scope));if(!usable.length)throw Object.assign(new Error("Permission denied"),{status:403});return usable;}
