import { pool,transaction,audit } from "./db.mjs";
import { jsonBody,requestContext,requirePermission,requireScopes,requireSession,send } from "./http.mjs";

const definitions={
  services:{table:"services",permission:"services",module:"clients",columns:["company_id","name","description","standard_price","currency","configured_by"],required:["name"],companyColumn:"company_id",actorColumn:"configured_by",defaults:{currency:"RWF"}},
  packages:{table:"packages",permission:"packages",module:"clients",columns:["company_id","name","price","currency","duration_days","is_special","created_by"],required:["name","price"],companyColumn:"company_id",defaults:{currency:"RWF"},actorColumn:"created_by"},
  meetings:{table:"meetings",permission:"meetings",module:"operations",columns:["company_id","title","starts_at","ends_at","department_id","agenda","notes","decisions","created_by"],required:["title","starts_at","ends_at"],companyColumn:"company_id",actorColumn:"created_by"},
  "daily-reports":{table:"daily_reports",permission:"daily_reports",module:"operations",columns:["employee_id","report_date","completed_today","pending_work","blockers","next_actions"],required:["report_date","completed_today","next_actions"],actorColumn:"employee_id",companyJoin:"JOIN employees e ON e.id=r.employee_id",companyExpr:"e.company_id"},
  "disciplinary-cases":{table:"disciplinary_cases",permission:"discipline",module:"people",columns:["company_id","employee_id","warning_type","warning_level","reason","incident_date","manager_id","expires_on","status"],required:["employee_id","warning_type","warning_level","reason","incident_date"],companyColumn:"company_id",actorColumn:"manager_id",defaults:{status:"draft"}},
  "job-openings":{table:"job_openings",permission:"recruitment",module:"people",columns:["company_id","department_id","title","description","hiring_manager_id","positions","status"],required:["department_id","title"],companyColumn:"company_id",actorColumn:"hiring_manager_id",defaults:{positions:1,status:"draft"}},
  candidates:{table:"candidates",permission:"recruitment",module:"people",columns:["job_opening_id","name","email","phone","stage","score","salary_proposal","currency","document_name","document_reference","notes"],required:["job_opening_id","name"],defaults:{stage:"applicant",currency:"RWF"},companyJoin:"JOIN job_openings jo ON jo.id=r.job_opening_id",companyExpr:"jo.company_id"},
  complaints:{table:"client_complaints",permission:"complaints",module:"clients",columns:["company_id","customer_id","reference","issue","priority","responsible_employee_id","deadline","escalation_level","status"],required:["customer_id","reference","issue","responsible_employee_id","deadline"],companyColumn:"company_id",defaults:{priority:"normal",escalation_level:"employee",status:"open"}},
  "client-reports":{table:"client_performance_reports",permission:"client_reports",module:"clients",columns:["company_id","customer_id","contract_id","period_start","period_end","status","observations","recommendations","next_priorities","created_by"],required:["customer_id","contract_id","period_start","period_end"],companyColumn:"company_id",actorColumn:"created_by",defaults:{status:"draft"}},
  suppliers:{table:"suppliers",permission:"suppliers",module:"resources",columns:["company_id","name","contact","category","notes"],required:["name"],companyColumn:"company_id"},
  subscriptions:{table:"subscriptions",permission:"subscriptions",module:"resources",columns:["company_id","supplier_id","name","plan","cost","currency","billing_cycle","expires_on","responsible_department_id","responsible_employee_id"],required:["name","cost","billing_cycle"],companyColumn:"company_id",defaults:{currency:"RWF"}},
  budgets:{table:"budgets",permission:"budgets",module:"finance",columns:["company_id","department_id","period_start","period_end","amount","currency","status"],required:["department_id","period_start","period_end","amount"],companyColumn:"company_id",defaults:{currency:"RWF",status:"draft"}},
  invoices:{table:"invoices",permission:"invoices",module:"finance",columns:["company_id","customer_id","contract_id","invoice_number","issued_on","due_on","subtotal","tax","currency","status"],required:["customer_id","invoice_number","issued_on","due_on","subtotal"],companyColumn:"company_id",defaults:{tax:0,currency:"RWF",status:"draft"}},
  payroll:{table:"payroll_runs",permission:"payroll",module:"finance",columns:["company_id","month","status","total_payable","currency","payment_reference","payment_date"],required:["month"],companyColumn:"company_id",defaults:{status:"draft",total_payable:0,currency:"RWF"}},
  commissions:{table:"commissions",permission:"commissions",module:"finance",columns:["employee_id","contract_id","rule_id","amount","currency","status"],required:["employee_id","contract_id","rule_id","amount"],defaults:{currency:"RWF",status:"pending"},companyJoin:"JOIN employees e ON e.id=r.employee_id",companyExpr:"e.company_id"},
  "asset-requests":{table:"asset_requests",permission:"assets",module:"resources",columns:["company_id","employee_id","asset_id","request_type","description","needed_by","status"],required:["request_type","description"],companyColumn:"company_id",actorColumn:"employee_id",defaults:{status:"draft"}},
  "document-references":{table:"document_references",permission:"documents",module:"administration",columns:["company_id","entity_type","entity_id","document_name","reference_number","created_by"],required:["entity_type","entity_id","document_name","reference_number"],companyColumn:"company_id",actorColumn:"created_by"},
};

const camel=value=>value.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase());
const bodyValue=(body,column)=>body[camel(column)]??body[column];
function companyClause(def,index=1){if(def.companyColumn)return `r.${def.companyColumn}=$${index}`;if(def.companyExpr)return `${def.companyExpr}=$${index}`;return `EXISTS(SELECT 1 FROM companies c WHERE c.id=$${index})`;}
function scopeClause(def,scopes,start=2){if(scopes.includes("company"))return{sql:"",values:[]};const parts=[],values=[];if(scopes.includes("self")&&def.actorColumn){values.push("employee");parts.push(`r.${def.actorColumn}=$${start+values.length-1}`);}if(scopes.includes("assigned")){const assigned=def.columns.find(column=>["employee_id","responsible_employee_id","responsible_employee_id","requested_by","created_by"].includes(column));if(assigned){values.push("employee");parts.push(`r.${assigned}=$${start+values.length-1}`);}}if(scopes.includes("department")){const department=def.columns.find(column=>["department_id","responsible_department_id"].includes(column));if(department){values.push("department");parts.push(`r.${department}=$${start+values.length-1}`);}}return{sql:parts.length?` AND (${parts.join(" OR ")})`:" AND false",values};}

export function registerResourceRoutes(route){for(const [path,def] of Object.entries(definitions)){
  route("GET",new RegExp(`^/api/${path}$`),async(req,res)=>{const s=await requireSession(req);const scopes=await requireScopes(s.employee_id,`${def.permission}.view`,["company","department","assigned","self"]);const join=def.companyJoin||"";const scoped=scopeClause(def,scopes);const values=[s.company_id,...scoped.values.map(value=>value==="employee"?s.employee_id:s.department_id)];const {rows}=await pool.query(`SELECT r.* FROM ${def.table} r ${join} WHERE ${companyClause(def)}${scoped.sql} ORDER BY r.id DESC LIMIT 500`,values);send(res,200,{data:rows});});
  route("POST",new RegExp(`^/api/${path}$`),async(req,res)=>{const s=await requireSession(req);await requirePermission(s.employee_id,`${def.permission}.create`,["company","department","self"]);const body=await jsonBody(req);for(const field of def.required)if(bodyValue(body,field)===undefined||bodyValue(body,field)==="")throw Object.assign(new Error(`${camel(field)} is required`),{status:400});const columns=[];const values=[];for(const column of def.columns){let value=bodyValue(body,column);if(column===def.companyColumn)value=s.company_id;if(column===def.actorColumn)value=s.employee_id;if(value===undefined)value=def.defaults?.[column];if(value!==undefined){columns.push(column);values.push(value);}}const placeholders=values.map((_,i)=>`$${i+1}`).join(",");const context=requestContext(req);const record=await transaction(async client=>{const {rows}=await client.query(`INSERT INTO ${def.table}(${columns.join(",")}) VALUES(${placeholders}) RETURNING *`,values);await audit(client,{companyId:s.company_id,actorId:s.employee_id,action:`${def.permission}.create`,module:def.module,entityType:def.table,entityId:rows[0].id,after:rows[0],requestId:context.requestId,ip:context.ip,userAgent:context.userAgent});return rows[0];});send(res,201,{data:record});});
  route("PATCH",new RegExp(`^/api/${path}/([0-9a-f-]+)$`),async(req,res,match)=>{const s=await requireSession(req);const scopes=await requireScopes(s.employee_id,`${def.permission}.edit`,["company","department","assigned","self"]);const body=await jsonBody(req);const changes=[];const values=[];for(const column of def.columns.filter(value=>![def.companyColumn,def.actorColumn].includes(value))){const value=bodyValue(body,column);if(value!==undefined){values.push(value);changes.push(`${column}=$${values.length}`);}}if(!changes.length)throw Object.assign(new Error("No editable fields supplied"),{status:400});const context=requestContext(req);const record=await transaction(async client=>{const scoped=scopeClause(def,scopes,3);const scopeValues=scoped.values.map(value=>value==="employee"?s.employee_id:s.department_id);const before=(await client.query(`SELECT r.* FROM ${def.table} r ${def.companyJoin||""} WHERE r.id=$1 AND ${companyClause(def,2)}${scoped.sql} FOR UPDATE`,[match[1],s.company_id,...scopeValues])).rows[0];if(!before)throw Object.assign(new Error("Record not found"),{status:404});values.push(match[1]);const {rows}=await client.query(`UPDATE ${def.table} SET ${changes.join(",")} WHERE id=$${values.length} RETURNING *`,values);await audit(client,{companyId:s.company_id,actorId:s.employee_id,action:`${def.permission}.edit`,module:def.module,entityType:def.table,entityId:match[1],before,after:rows[0],requestId:context.requestId,ip:context.ip,userAgent:context.userAgent});return rows[0];});send(res,200,{data:record});});
 }}
