import { pool,transaction } from "./db.mjs";
import { hashPassword,temporaryPassword } from "./security.mjs";

const bootstrapPassword=process.env.FRAME_BOOTSTRAP_PASSWORD||temporaryPassword();
const passwordHash=await hashPassword(bootstrapPassword);
const result=await transaction(async client=>{
  const company=(await client.query(`INSERT INTO companies(name,code,country_code,timezone,base_currency) VALUES('FRAME Media Agency','FRAME','RW','Africa/Kigali','RWF') ON CONFLICT(code) DO UPDATE SET timezone=EXCLUDED.timezone RETURNING id`)).rows[0];
  for(const namespace of ["employee","customer","contract","invoice","asset","purchase_request"])await client.query("INSERT INTO reference_counters(company_id,namespace,next_value) VALUES($1,$2,1) ON CONFLICT DO NOTHING",[company.id,namespace]);
  const department=(await client.query("INSERT INTO departments(company_id,name,code) VALUES($1,'Administration','ADM') ON CONFLICT(company_id,code) DO UPDATE SET name=EXCLUDED.name RETURNING id",[company.id])).rows[0];
  const employee=(await client.query(`INSERT INTO employees(company_id,employee_number,department_id,first_name,last_name,work_email,job_title,status) VALUES($1,'FRM-0001',$2,'System','Administrator','admin@frame.local','Super Admin','active') ON CONFLICT(company_id,employee_number) DO UPDATE SET status='active' RETURNING id`,[company.id,department.id])).rows[0];
  await client.query("UPDATE reference_counters SET next_value=greatest(next_value,2) WHERE company_id=$1 AND namespace='employee'",[company.id]);
  await client.query(`INSERT INTO user_accounts(employee_id,password_hash,must_change_password,temporary_password_expires_at) VALUES($1,$2,true,now()+interval '24 hours') ON CONFLICT(employee_id) DO UPDATE SET password_hash=EXCLUDED.password_hash,must_change_password=true,temporary_password_expires_at=EXCLUDED.temporary_password_expires_at`,[employee.id,passwordHash]);
  const role=(await client.query("INSERT INTO roles(company_id,name,description,is_system) VALUES($1,'Super Admin','Unrestricted audited administration',true) ON CONFLICT(company_id,name) DO UPDATE SET status='active' RETURNING id",[company.id])).rows[0];
  const resources=["services","packages","meetings","daily_reports","discipline","recruitment","complaints","client_reports","suppliers","subscriptions","budgets","invoices","payroll","commissions","documents","asset-requests"];
  const permissionKeys=["dashboard.view","search.global","departments.view","departments.create","departments.edit","employees.view","employees.create","employees.edit","employees.reset_password","employees.exit","customers.view","customers.create","customers.edit","customers.reassign","tasks.view","tasks.create","tasks.edit","contracts.view","contracts.create","contracts.edit","contracts.submit","kpi.view","kpi.create","kpi.submit","kpi.finalize","kpi_documents.view","kpi_documents.upload","employee_contracts.view","employee_contracts.upload","leave.view","leave.create","expenses.view","expenses.create","expenses.edit","expenses.submit","assets.view","assets.create","assets.edit","assets.assign","assets.submit","procurement.view","procurement.create","procurement.edit","procurement.submit","attendance.view","accounting.view","reports.view","reports.export","payroll.calculate","payroll.mark_paid","payroll.submit","budgets.submit","packages.submit","recruitment.hire","recruitment.submit","daily_reports.submit","complaints.escalate","client_reports.deliver","approvals.view","approvals.approve","approvals.reject","audit.view","audit.gm_activity","roles.configure",...resources.flatMap(resource=>[`${resource}.view`,`${resource}.create`,`${resource}.edit`])];
  for(const key of permissionKeys){const permission=(await client.query("INSERT INTO permissions(permission_key,description) VALUES($1,$2) ON CONFLICT(permission_key) DO UPDATE SET description=EXCLUDED.description RETURNING id",[key,key])).rows[0];await client.query("INSERT INTO role_permissions(role_id,permission_id,scope) VALUES($1,$2,'company') ON CONFLICT DO NOTHING",[role.id,permission.id]);}
  await client.query("INSERT INTO employee_roles(employee_id,role_id,assigned_by) VALUES($1,$2,$1) ON CONFLICT DO NOTHING",[employee.id,role.id]);
  for(const key of ["accounting.create","accounting.post"]){const permission=(await client.query("INSERT INTO permissions(permission_key,description) VALUES($1,$1) ON CONFLICT(permission_key) DO UPDATE SET description=EXCLUDED.description RETURNING id",[key])).rows[0];await client.query("INSERT INTO role_permissions(role_id,permission_id,scope) VALUES($1,$2,'company') ON CONFLICT DO NOTHING",[role.id,permission.id]);}
  return{employeeNumber:"FRM-0001",bootstrapPassword};
});
console.log(JSON.stringify({message:"FRAME OS bootstrap complete",...result}));
await pool.end();
