import { transaction,audit } from "./db.mjs";
import { jsonBody,requestContext,requirePermission,requireSession,send } from "./http.mjs";

async function workflow(client,{companyId,key,name,steps,createdBy}){let definition=(await client.query("SELECT id FROM workflow_definitions WHERE company_id=$1 AND workflow_key=$2 AND status='active' ORDER BY version DESC LIMIT 1",[companyId,key])).rows[0];if(!definition){definition=(await client.query("INSERT INTO workflow_definitions(company_id,workflow_key,name,version,definition,created_by) VALUES($1,$2,$3,1,$4,$5) RETURNING id",[companyId,key,name,JSON.stringify(steps),createdBy])).rows[0];}return definition.id;}
async function submit(client,{session,entityType,entityId,title,key,name,steps}){const definitionId=await workflow(client,{companyId:session.company_id,key,name,steps,createdBy:session.employee_id});const request=(await client.query("INSERT INTO approval_requests(company_id,workflow_definition_id,entity_type,entity_id,title,requested_by,status,submitted_at) VALUES($1,$2,$3,$4,$5,$6,'pending',now()) RETURNING *",[session.company_id,definitionId,entityType,entityId,title,session.employee_id])).rows[0];for(const [index,step] of steps.entries())await client.query("INSERT INTO approval_steps(request_id,step_number,assignee_type,assignee_ref,status) VALUES($1,$2,$3,$4,$5)",[request.id,index+1,step.type,step.ref,index===0?"pending":"waiting"]);return request;}
export function registerWorkflowRoutes(route){
 route("POST",/^\/api\/contracts\/([0-9a-f-]+)\/submit$/,async(req,res,match)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"contracts.submit",["company","department","assigned"]);const context=requestContext(req);const request=await transaction(async c=>{const contract=(await c.query("SELECT * FROM contracts WHERE id=$1 AND company_id=$2 AND status='draft' FOR UPDATE",[match[1],s.company_id])).rows[0];if(!contract)throw Object.assign(new Error("Draft contract not found"),{status:404});const result=await submit(c,{session:s,entityType:"contract",entityId:contract.id,title:`Approve ${contract.contract_number}`,key:"contract_activation",name:"Contract activation",steps:[{type:"role",ref:"Sales Manager"},{type:"role",ref:"General Manager"}]});await c.query("UPDATE contracts SET status='pending_sales_manager' WHERE id=$1",[contract.id]);await audit(c,{companyId:s.company_id,actorId:s.employee_id,action:"contracts.submit",module:"clients",entityType:"contract",entityId:contract.id,before:contract,after:{status:"pending_sales_manager"},requestId:context.requestId,ip:context.ip,userAgent:context.userAgent});return result;});send(res,201,{data:request});});
 route("POST",/^\/api\/kpi-plans\/([0-9a-f-]+)\/submit$/,async(req,res,match)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"kpi.submit",["company","department"]);const request=await transaction(async c=>{const plan=(await c.query("SELECT * FROM monthly_kpi_plans WHERE id=$1 AND company_id=$2 AND status='draft' FOR UPDATE",[match[1],s.company_id])).rows[0];if(!plan)throw Object.assign(new Error("Draft KPI plan not found"),{status:404});const result=await submit(c,{session:s,entityType:"monthly_kpi_plan",entityId:plan.id,title:"Approve monthly KPI plan",key:"monthly_kpi",name:"Monthly KPI",steps:[{type:"role",ref:"HR Manager"},{type:"role",ref:"General Manager"},{type:"role",ref:"CEO"}]});await c.query("UPDATE monthly_kpi_plans SET status='pending_hr' WHERE id=$1",[plan.id]);return result;});send(res,201,{data:request});});
 route("POST",/^\/api\/leave\/([0-9a-f-]+)\/submit$/,async(req,res,match)=>{const s=await requireSession(req);const request=await transaction(async c=>{const leave=(await c.query("SELECT l.*,e.manager_id FROM leave_requests l JOIN employees e ON e.id=l.employee_id WHERE l.id=$1 AND e.company_id=$2 AND l.employee_id=$3 AND l.status='draft' FOR UPDATE OF l",[match[1],s.company_id,s.employee_id])).rows[0];if(!leave)throw Object.assign(new Error("Draft leave request not found"),{status:404});if(!leave.manager_id)throw Object.assign(new Error("A reporting manager must be assigned before leave can be submitted"),{status:409});const policy=(await c.query("SELECT requires_balance FROM leave_policies WHERE company_id=$1 AND leave_type=$2 AND status='active'",[s.company_id,leave.leave_type])).rows[0];if(!policy)throw Object.assign(new Error("This leave type is not configured"),{status:400});if(policy.requires_balance){const year=new Date(leave.starts_on).getUTCFullYear();const balance=(await c.query("SELECT entitled_days+carried_days-used_days-reserved_days available FROM leave_balances WHERE employee_id=$1 AND leave_type=$2 AND balance_year=$3 FOR UPDATE",[s.employee_id,leave.leave_type,year])).rows[0];if(!balance||Number(balance.available)<Number(leave.total_days))throw Object.assign(new Error("Insufficient leave balance"),{status:409});await c.query("UPDATE leave_balances SET reserved_days=reserved_days+$4,updated_at=now() WHERE employee_id=$1 AND leave_type=$2 AND balance_year=$3",[s.employee_id,leave.leave_type,year,leave.total_days]);}const result=await submit(c,{session:s,entityType:"leave_request",entityId:leave.id,title:`${leave.leave_type} leave request`,key:"leave",name:"Leave approval",steps:[{type:"manager",ref:"direct"},{type:"role",ref:"HR Manager"}]});await c.query("UPDATE leave_requests SET status='pending',approval_request_id=$2,submitted_at=now() WHERE id=$1",[leave.id,result.id]);return result;});send(res,201,{data:request});});
 route("POST",/^\/api\/tasks\/([0-9a-f-]+)\/submit$/,async(req,res,match)=>{const s=await requireSession(req);const b=await jsonBody(req);if(!b.evidence)throw Object.assign(new Error("Evidence is required"),{status:400});const value=await transaction(async c=>{const task=(await c.query("SELECT * FROM tasks WHERE id=$1 AND company_id=$2 AND assignee_id=$3 AND status IN ('assigned','in_progress','correction') FOR UPDATE",[match[1],s.company_id,s.employee_id])).rows[0];if(!task)throw Object.assign(new Error("Task cannot be submitted"),{status:409});const revision=(await c.query("SELECT COALESCE(max(revision),0)+1 revision FROM task_submissions WHERE task_id=$1",[task.id])).rows[0].revision;const submission=(await c.query("INSERT INTO task_submissions(task_id,revision,submitted_by,evidence,status) VALUES($1,$2,$3,$4,'submitted') RETURNING *",[task.id,revision,s.employee_id,b.evidence])).rows[0];await c.query("UPDATE tasks SET status='manager_review',submitted_at=now(),progress=100,updated_at=now() WHERE id=$1",[task.id]);return submission;});send(res,201,{data:value});});
 route("POST",/^\/api\/tasks\/([0-9a-f-]+)\/score$/,async(req,res,match)=>{const s=await requireSession(req);const b=await jsonBody(req);const score=Number(b.score);if(!Number.isInteger(score)||score<0||score>100)throw Object.assign(new Error("Score must be an integer from 0 to 100"),{status:400});const {rows}=await transaction(async c=>c.query("UPDATE tasks SET manager_score=$1,manager_note=$2,status='completed',completed_at=now(),updated_at=now() WHERE id=$3 AND company_id=$4 AND direct_manager_id=$5 AND status='manager_review' RETURNING *",[score,b.note||null,match[1],s.company_id,s.employee_id]));if(!rows[0])throw Object.assign(new Error("Task is not awaiting your review"),{status:409});send(res,200,{data:rows[0]});});
 route("POST",/^\/api\/tasks\/([0-9a-f-]+)\/reject$/,async(req,res,match)=>{const s=await requireSession(req);const b=await jsonBody(req);if(!b.note)throw Object.assign(new Error("Correction note is required"),{status:400});const task=await transaction(async c=>{const current=(await c.query("SELECT * FROM tasks WHERE id=$1 AND company_id=$2 AND direct_manager_id=$3 AND status='manager_review' FOR UPDATE",[match[1],s.company_id,s.employee_id])).rows[0];if(!current)throw Object.assign(new Error("Task is not awaiting your review"),{status:409});await c.query("UPDATE task_submissions SET status='rejected',reviewed_by=$2,review_note=$3 WHERE id=(SELECT id FROM task_submissions WHERE task_id=$1 ORDER BY revision DESC LIMIT 1)",[current.id,s.employee_id,b.note]);return(await c.query("UPDATE tasks SET status='correction',progress=90,manager_note=$2,updated_at=now() WHERE id=$1 RETURNING *",[current.id,b.note])).rows[0];});send(res,200,{data:task});});
 route("POST",/^\/api\/kpi-plans\/([0-9a-f-]+)\/finalize$/,async(req,res,match)=>{const s=await requireSession(req);await requirePermission(s.employee_id,"kpi.finalize",["company","department"]);const b=await jsonBody(req);const score=Number(b.finalScore),factor=Number(b.salaryFactor);if(!Number.isFinite(score)||score<0||score>100||!Number.isFinite(factor)||factor<0||factor>2)throw Object.assign(new Error("Final score (0-100) and salary factor (0-2) are required"),{status:400});const request=await transaction(async c=>{const plan=(await c.query("SELECT * FROM monthly_kpi_plans WHERE id=$1 AND company_id=$2 AND status='active' FOR UPDATE",[match[1],s.company_id])).rows[0];if(!plan)throw Object.assign(new Error("Active KPI plan not found"),{status:404});const result=await submit(c,{session:s,entityType:"monthly_kpi_final",entityId:plan.id,title:"Approve final monthly KPI score",key:"monthly_kpi_final",name:"Final KPI score",steps:[{type:"role",ref:"General Manager"},{type:"role",ref:"CEO"}]});await c.query("UPDATE monthly_kpi_plans SET status='final_review',final_score=$2,salary_factor=$3 WHERE id=$1",[plan.id,score,factor]);return result;});send(res,201,{data:request});});
 route("POST",/^\/api\/tasks\/([0-9a-f-]+)\/extend$/,async(req,res,match)=>{const s=await requireSession(req);const b=await jsonBody(req);if(!b.newDeadline||!b.reason)throw Object.assign(new Error("New deadline and reason are required"),{status:400});const value=await transaction(async c=>{const task=(await c.query("SELECT * FROM tasks WHERE id=$1 AND company_id=$2 AND direct_manager_id=$3 FOR UPDATE",[match[1],s.company_id,s.employee_id])).rows[0];if(!task)throw Object.assign(new Error("Task not found"),{status:404});const next=new Date(b.newDeadline),old=new Date(task.deadline);if(next<=old||next-old>259200000)throw Object.assign(new Error("Extension must be after the deadline and no more than 3 days"),{status:400});const extension=(await c.query("INSERT INTO task_deadline_extensions(task_id,old_deadline,new_deadline,reason,extended_by) VALUES($1,$2,$3,$4,$5) RETURNING *",[task.id,task.deadline,next,b.reason,s.employee_id])).rows[0];await c.query("UPDATE tasks SET deadline=$1,updated_at=now() WHERE id=$2",[next,task.id]);return extension;});send(res,201,{data:value});});

 const approvalConfigs={
  expenses:{table:"expense_requests",entityType:"expense_request",permission:"expenses.submit",title:"Approve expense request",key:"expense",name:"Expense approval",pendingSet:"status='pending'",steps:[{type:"manager",ref:"direct"},{type:"role",ref:"Finance"},{type:"role",ref:"General Manager"},{type:"role",ref:"CEO"}]},
  budgets:{table:"budgets",entityType:"budget",permission:"budgets.submit",title:"Approve department budget",key:"budget",name:"Budget approval",pendingSet:"status='pending'",steps:[{type:"role",ref:"Finance"},{type:"role",ref:"General Manager"},{type:"role",ref:"CEO"}]},
  payroll:{table:"payroll_runs",entityType:"payroll_run",permission:"payroll.submit",title:"Approve payroll",key:"payroll",name:"Payroll approval",pendingSet:"status='pending'",steps:[{type:"role",ref:"General Manager"},{type:"role",ref:"CEO"}]},
  "purchase-requests":{table:"purchase_requests",entityType:"purchase_request",permission:"procurement.submit",title:"Approve purchase request",key:"procurement",name:"Procurement approval",pendingSet:"status='pending'",steps:[{type:"manager",ref:"direct"},{type:"role",ref:"Finance"}]},
  "asset-requests":{table:"asset_requests",entityType:"asset_request",permission:"assets.submit",title:"Approve equipment request",key:"asset_request",name:"Equipment request",pendingSet:"status='pending'",steps:[{type:"manager",ref:"direct"}]},
  "special-packages":{table:"packages",entityType:"special_package",permission:"packages.submit",title:"Approve special package",key:"special_package",name:"Special package approval",pendingSet:"status='inactive'",steps:[{type:"role",ref:"General Manager"}],extra:"is_special=true"},
  "job-openings":{table:"job_openings",entityType:"job_opening",permission:"recruitment.submit",title:"Approve recruitment opening",key:"recruitment",name:"Recruitment approval",steps:[{type:"role",ref:"General Manager"},{type:"role",ref:"CEO"}]},
  "daily-reports":{table:"daily_reports",entityType:"daily_report",permission:"daily_reports.submit",title:"Review daily report",key:"daily_report",name:"Daily report approval",steps:[{type:"manager",ref:"direct"},{type:"role",ref:"General Manager"},{type:"role",ref:"HR Manager"}]},
 };
 for(const [path,config] of Object.entries(approvalConfigs))route("POST",new RegExp(`^/api/${path}/([0-9a-f-]+)/submit$`),async(req,res,match)=>{const s=await requireSession(req);await requirePermission(s.employee_id,config.permission,["company","department","self"]);const request=await transaction(async c=>{const conditions=config.extra?` AND ${config.extra}`:"";const record=(await c.query(`SELECT * FROM ${config.table} WHERE id=$1${config.table==='daily_reports'?' AND employee_id=$2':' '}${conditions} FOR UPDATE`,config.table==='daily_reports'?[match[1],s.employee_id]:[match[1]])).rows[0];if(!record)throw Object.assign(new Error("Draft record not found"),{status:404});const result=await submit(c,{session:s,entityType:config.entityType,entityId:record.id,title:config.title,key:config.key,name:config.name,steps:config.steps});if(config.pendingSet)await c.query(`UPDATE ${config.table} SET ${config.pendingSet} WHERE id=$1`,[record.id]);if('approval_request_id' in record)await c.query(`UPDATE ${config.table} SET approval_request_id=$2 WHERE id=$1`,[record.id,result.id]);return result;});send(res,201,{data:request});});
}
