export const companyConfiguration = {
  legalCountry: "Rwanda",
  countryCode: "RW",
  timezone: "Africa/Kigali",
  currency: "RWF",
  currencyName: "Rwandan franc",
  locale: "en-RW",
  launchDataStrategy: "clean-start",
  legacyImportEnabled: false,
  employeeAccountCreators: ["super_admin", "hr"],
  employeeCreationRequiresApproval: false,
  initialPasswordMode: "system-generated-temporary",
  requirePasswordChangeAtFirstLogin: true,
  temporaryPasswordExpiresHours: 24,
  twoFactorAuthentication: "disabled",
  sessionIdleTimeoutMinutes: 60,
  passwordResetAuthorities: ["super_admin", "hr"],
  passwordSelfServiceReset: false,
  supportedLanguages: ["en"],
  taxFeaturesEnabled: false,
  attendance: {
    restriction: "single-office-network",
    networkName: "FRAME MEDIA AGENCY",
    approvedCidrs: [] as string[],
  },
} as const;
